# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/dwca-codegen.csproj'
    configuration: $(BuildConfiguration)
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '**/dwca-codegen/bin/Release'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish Package as Build Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'NuGet package' 

