# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/dwca-codegen.csproj'
    versioningScheme: 'off'
    configuration: '$(BuildConfiguration)'
    packDirectory: '$(build.artifactStagingDirectory)'

# Publish Package as Build Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'NuGet package' 

